@url = https://8080-henriquerom-gamessw2202-yle95qtiioq.ws-us116.gitpod.io

GET {{url}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Counter Strike 2",
    "plataforma": 2
}

###
GET {{url}}/jogos/1