@url = https://8080-elisascaran-gamessw2202-w1cnpcjkbt6.ws-us116.gitpod.io

GET {{url}}/jogos

###
POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Barbie",
    "plataforma":  [
        {"id": 1},
        {"id": 2}
    ]
}

