@url = https://8080-elisascaran-gamessw2202-w1cnpcjkbt6.ws-us116.gitpod.io

GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "PC fds"
}

###
GET {{url}}/plataformas/1